### ISSUE TITLE
frozendict __eq__ is broken for comparison with dicts

### ISSUE THREAD

**Issue by kevints** [wickman/pystachio#18] opened 2015-09-29 22:12 UTC
```
    assert r == {}
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = frozendict({'request_id': 834}), other = {}

>   ???
E   AttributeError: 'dict' object has no attribute '_frozendict__key'
```

**Comment by kevints** [comment] 2015-09-29 22:13
This is unexpected given the behavior of frozenset:

```
>>> frozenset([1, 2]) == set([2, 1])
True
>>> 
```

**Comment by tomtwttr** [comment] 2020-03-10 22:15
Unable to reproduce, or fixed in https://github.com/wickman/pystachio/pull/38.

**Closed by tomtwttr** 2020-03-10 22:15 UTC
